service: debs-serverless-api
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}
    STAGE: ${opt:stage, 'dev'}
    IS_OFFLINE: ${opt:isOffline, 'false'}

plugins:
  - serverless-offline

functions:
  LambdaDebts:
    name: LambdaDebts-${opt:stage, 'dev'}
    handler: src/infrastructure/lambdas/handler.handler
    events:
      # Rutas para TypeDebt
      - http:
          path: /type-debts
          method: get
          cors: true
      - http:
          path: /type-debts
          method: post
          cors: true
      - http:
          path: /type-debts/{id}
          method: put
          cors: true
      - http:
          path: /type-debts/{id}
          method: delete
          cors: true
      # Rutas para VehicleDebt
      - http:
          path: /vehicle-debts
          method: get
          cors: true
      - http:
          path: /vehicle-debts
          method: post
          cors: true
      - http:
          path: /vehicle-debts/{id}
          method: put
          cors: true
      - http:
          path: /vehicle-debts/{id}
          method: delete
          cors: true
      # Ruta para obtener deudas por vehicle_id
      - http:
          path: /vehicles/{vehicleId}/debts
          method: get
          cors: true
